<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@839.v35e2736cfd5c">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@3668.v1763b_b_6ccffd">
    <parentIds>
      <string>53</string>
    </parentIds>
    <id>54</id>
    <descriptorId>org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@3668.v1763b_b_6ccffd">
      <arguments>
        <entry>
          <string>script</string>
          <string>
                        set +x
                        cd MultiRegion
                        terraform ${action} --auto-approve --var=&quot;aws_access_key=${AWS_ACCESS_KEY_ID}&quot; --var=&quot;aws_secret_key=${AWS_SECRET_ACCESS_KEY}&quot; --var=&quot;aws_region=${aws_region}&quot; --var=&quot;subnet_count=${subnet_count}&quot;
                    </string>
        </entry>
      </arguments>
      <sensitiveVariables>
        <string>AWS_ACCESS_KEY_ID</string>
        <string>AWS_SECRET_ACCESS_KEY</string>
      </sensitiveVariables>
      <isUnmodifiedBySanitization>true</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@1213.v646def1087f9">
      <startTime>1696402493312</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <wf.a.ErrorAction plugin="workflow-api@1213.v646def1087f9">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@639.v6eca_cd8c04a_a_">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1171)</trace>
          <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2.lambda$interrupt$0(WorkflowRun.java:398)</trace>
          <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions>
          <wf.a.ErrorAction_-ErrorId plugin="workflow-api@1213.v646def1087f9">
            <stackTrace/>
            <suppressedExceptions class="empty-list"/>
            <uuid>87d54afa-cbea-4236-83a9-027a0f0a070a</uuid>
          </wf.a.ErrorAction_-ErrorId>
        </suppressedExceptions>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <jenkins.model.CauseOfInterruption_-UserInterruption>
              <user>jenkinsadmin</user>
            </jenkins.model.CauseOfInterruption_-UserInterruption>
          </a>
        </causes>
        <actualInterruption>true</actualInterruption>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>